//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mictlanix.Fel.Client.Internals {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaTFD", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.Negocios")]
    [System.SerializableAttribute()]
    public partial class RespuestaTFD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorDetalladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PDFResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Timbre TimbreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRespuestaField, value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeErrorDetallado {
            get {
                return this.MensajeErrorDetalladoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorDetalladoField, value) != true)) {
                    this.MensajeErrorDetalladoField = value;
                    this.RaisePropertyChanged("MensajeErrorDetallado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PDFResultado {
            get {
                return this.PDFResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.PDFResultadoField, value) != true)) {
                    this.PDFResultadoField = value;
                    this.RaisePropertyChanged("PDFResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Timbre Timbre {
            get {
                return this.TimbreField;
            }
            set {
                if ((object.ReferenceEquals(this.TimbreField, value) != true)) {
                    this.TimbreField = value;
                    this.RaisePropertyChanged("Timbre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLResultado {
            get {
                return this.XMLResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLResultadoField, value) != true)) {
                    this.XMLResultadoField = value;
                    this.RaisePropertyChanged("XMLResultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timbre", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.Negocios")]
    [System.SerializableAttribute()]
    public partial class Timbre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaTimbradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCertificadoSATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelloCFDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelloSATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaTimbrado {
            get {
                return this.FechaTimbradoField;
            }
            set {
                if ((this.FechaTimbradoField.Equals(value) != true)) {
                    this.FechaTimbradoField = value;
                    this.RaisePropertyChanged("FechaTimbrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCertificadoSAT {
            get {
                return this.NumeroCertificadoSATField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCertificadoSATField, value) != true)) {
                    this.NumeroCertificadoSATField = value;
                    this.RaisePropertyChanged("NumeroCertificadoSAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelloCFD {
            get {
                return this.SelloCFDField;
            }
            set {
                if ((object.ReferenceEquals(this.SelloCFDField, value) != true)) {
                    this.SelloCFDField = value;
                    this.RaisePropertyChanged("SelloCFD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelloSAT {
            get {
                return this.SelloSATField;
            }
            set {
                if ((object.ReferenceEquals(this.SelloSATField, value) != true)) {
                    this.SelloSATField = value;
                    this.RaisePropertyChanged("SelloSAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCancelacion", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.Negocios")]
    [System.SerializableAttribute()]
    public partial class RespuestaCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DetalleCancelacion[] DetallesCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorDetalladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLAcuseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DetalleCancelacion[] DetallesCancelacion {
            get {
                return this.DetallesCancelacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesCancelacionField, value) != true)) {
                    this.DetallesCancelacionField = value;
                    this.RaisePropertyChanged("DetallesCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeErrorDetallado {
            get {
                return this.MensajeErrorDetalladoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorDetalladoField, value) != true)) {
                    this.MensajeErrorDetalladoField = value;
                    this.RaisePropertyChanged("MensajeErrorDetallado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLAcuse {
            get {
                return this.XMLAcuseField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLAcuseField, value) != true)) {
                    this.XMLAcuseField = value;
                    this.RaisePropertyChanged("XMLAcuse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCancelacion", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.Negocios")]
    [System.SerializableAttribute()]
    public partial class DetalleCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoResultado {
            get {
                return this.CodigoResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoResultadoField, value) != true)) {
                    this.CodigoResultadoField = value;
                    this.RaisePropertyChanged("CodigoResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeResultado {
            get {
                return this.MensajeResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeResultadoField, value) != true)) {
                    this.MensajeResultadoField = value;
                    this.RaisePropertyChanged("MensajeResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCreditos", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.Negocios")]
    [System.SerializableAttribute()]
    public partial class RespuestaCreditos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DetallesPaqueteCreditos[] PaquetesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DetallesPaqueteCreditos[] Paquetes {
            get {
                return this.PaquetesField;
            }
            set {
                if ((object.ReferenceEquals(this.PaquetesField, value) != true)) {
                    this.PaquetesField = value;
                    this.RaisePropertyChanged("Paquetes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallesPaqueteCreditos", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.Negocios")]
    [System.SerializableAttribute()]
    public partial class DetallesPaqueteCreditos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnUsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaActivacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaqueteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimbresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimbresRestantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimbresUsadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VigenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnUso {
            get {
                return this.EnUsoField;
            }
            set {
                if ((this.EnUsoField.Equals(value) != true)) {
                    this.EnUsoField = value;
                    this.RaisePropertyChanged("EnUso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaActivacion {
            get {
                return this.FechaActivacionField;
            }
            set {
                if ((this.FechaActivacionField.Equals(value) != true)) {
                    this.FechaActivacionField = value;
                    this.RaisePropertyChanged("FechaActivacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paquete {
            get {
                return this.PaqueteField;
            }
            set {
                if ((object.ReferenceEquals(this.PaqueteField, value) != true)) {
                    this.PaqueteField = value;
                    this.RaisePropertyChanged("Paquete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Timbres {
            get {
                return this.TimbresField;
            }
            set {
                if ((this.TimbresField.Equals(value) != true)) {
                    this.TimbresField = value;
                    this.RaisePropertyChanged("Timbres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimbresRestantes {
            get {
                return this.TimbresRestantesField;
            }
            set {
                if ((this.TimbresRestantesField.Equals(value) != true)) {
                    this.TimbresRestantesField = value;
                    this.RaisePropertyChanged("TimbresRestantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimbresUsados {
            get {
                return this.TimbresUsadosField;
            }
            set {
                if ((this.TimbresUsadosField.Equals(value) != true)) {
                    this.TimbresUsadosField = value;
                    this.RaisePropertyChanged("TimbresUsados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vigente {
            get {
                return this.VigenteField;
            }
            set {
                if ((this.VigenteField.Equals(value) != true)) {
                    this.VigenteField = value;
                    this.RaisePropertyChanged("Vigente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaReporte", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.Negocios")]
    [System.SerializableAttribute()]
    public partial class RespuestaReporte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RegistroTimbre[] ListaComprobantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalComprobantesPeriodoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RegistroTimbre[] ListaComprobantes {
            get {
                return this.ListaComprobantesField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaComprobantesField, value) != true)) {
                    this.ListaComprobantesField = value;
                    this.RaisePropertyChanged("ListaComprobantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalComprobantesPeriodo {
            get {
                return this.TotalComprobantesPeriodoField;
            }
            set {
                if ((this.TotalComprobantesPeriodoField.Equals(value) != true)) {
                    this.TotalComprobantesPeriodoField = value;
                    this.RaisePropertyChanged("TotalComprobantesPeriodo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistroTimbre", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.Negocios")]
    [System.SerializableAttribute()]
    public partial class RegistroTimbre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaTimbradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoFilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaTimbrado {
            get {
                return this.FechaTimbradoField;
            }
            set {
                if ((this.FechaTimbradoField.Equals(value) != true)) {
                    this.FechaTimbradoField = value;
                    this.RaisePropertyChanged("FechaTimbrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoFila {
            get {
                return this.NoFilaField;
            }
            set {
                if ((this.NoFilaField.Equals(value) != true)) {
                    this.NoFilaField = value;
                    this.RaisePropertyChanged("NoFila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCEmisor {
            get {
                return this.RFCEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCEmisorField, value) != true)) {
                    this.RFCEmisorField = value;
                    this.RaisePropertyChanged("RFCEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCReceptor {
            get {
                return this.RFCReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCReceptorField, value) != true)) {
                    this.RFCReceptorField = value;
                    this.RaisePropertyChanged("RFCReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSFEL.IWSTFD")]
    public interface IWSTFD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/TimbrarCFDI", ReplyAction="http://tempuri.org/IWSTFD/TimbrarCFDIResponse")]
        RespuestaTFD TimbrarCFDI(string usuario, string password, string cadenaXML, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/TimbrarCFDI", ReplyAction="http://tempuri.org/IWSTFD/TimbrarCFDIResponse")]
        System.Threading.Tasks.Task<RespuestaTFD> TimbrarCFDIAsync(string usuario, string password, string cadenaXML, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/CancelarCFDI", ReplyAction="http://tempuri.org/IWSTFD/CancelarCFDIResponse")]
        RespuestaCancelacion CancelarCFDI(string usuario, string password, string rFCEmisor, string[] listaCFDI, string clavePrivada_Base64, string passwordClavePrivada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/CancelarCFDI", ReplyAction="http://tempuri.org/IWSTFD/CancelarCFDIResponse")]
        System.Threading.Tasks.Task<RespuestaCancelacion> CancelarCFDIAsync(string usuario, string password, string rFCEmisor, string[] listaCFDI, string clavePrivada_Base64, string passwordClavePrivada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/TimbrarCFDTestSectorPrimario", ReplyAction="http://tempuri.org/IWSTFD/TimbrarCFDTestSectorPrimarioResponse")]
        RespuestaTFD TimbrarCFDTestSectorPrimario(string usuario, string password, string cadenaXML, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/TimbrarCFDTestSectorPrimario", ReplyAction="http://tempuri.org/IWSTFD/TimbrarCFDTestSectorPrimarioResponse")]
        System.Threading.Tasks.Task<RespuestaTFD> TimbrarCFDTestSectorPrimarioAsync(string usuario, string password, string cadenaXML, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ObtenerPDF", ReplyAction="http://tempuri.org/IWSTFD/ObtenerPDFResponse")]
        RespuestaTFD ObtenerPDF(string usuario, string password, string uUID, string LogoBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ObtenerPDF", ReplyAction="http://tempuri.org/IWSTFD/ObtenerPDFResponse")]
        System.Threading.Tasks.Task<RespuestaTFD> ObtenerPDFAsync(string usuario, string password, string uUID, string LogoBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ObtenerAcuseEnvio", ReplyAction="http://tempuri.org/IWSTFD/ObtenerAcuseEnvioResponse")]
        RespuestaTFD ObtenerAcuseEnvio(string usuario, string password, string uUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ObtenerAcuseEnvio", ReplyAction="http://tempuri.org/IWSTFD/ObtenerAcuseEnvioResponse")]
        System.Threading.Tasks.Task<RespuestaTFD> ObtenerAcuseEnvioAsync(string usuario, string password, string uUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ObtenerAcuseCancelacion", ReplyAction="http://tempuri.org/IWSTFD/ObtenerAcuseCancelacionResponse")]
        RespuestaTFD ObtenerAcuseCancelacion(string usuario, string password, string uUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ObtenerAcuseCancelacion", ReplyAction="http://tempuri.org/IWSTFD/ObtenerAcuseCancelacionResponse")]
        System.Threading.Tasks.Task<RespuestaTFD> ObtenerAcuseCancelacionAsync(string usuario, string password, string uUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/CambiarPassword", ReplyAction="http://tempuri.org/IWSTFD/CambiarPasswordResponse")]
        RespuestaTFD CambiarPassword(string usuario, string passwordActual, string passwordNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/CambiarPassword", ReplyAction="http://tempuri.org/IWSTFD/CambiarPasswordResponse")]
        System.Threading.Tasks.Task<RespuestaTFD> CambiarPasswordAsync(string usuario, string passwordActual, string passwordNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ConsultarComplementoTimbre", ReplyAction="http://tempuri.org/IWSTFD/ConsultarComplementoTimbreResponse")]
        RespuestaTFD ConsultarComplementoTimbre(string usuario, string password, string uUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ConsultarComplementoTimbre", ReplyAction="http://tempuri.org/IWSTFD/ConsultarComplementoTimbreResponse")]
        System.Threading.Tasks.Task<RespuestaTFD> ConsultarComplementoTimbreAsync(string usuario, string password, string uUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ConsultarTimbrePorReferencia", ReplyAction="http://tempuri.org/IWSTFD/ConsultarTimbrePorReferenciaResponse")]
        RespuestaTFD ConsultarTimbrePorReferencia(string usuario, string password, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ConsultarTimbrePorReferencia", ReplyAction="http://tempuri.org/IWSTFD/ConsultarTimbrePorReferenciaResponse")]
        System.Threading.Tasks.Task<RespuestaTFD> ConsultarTimbrePorReferenciaAsync(string usuario, string password, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ConsultarCreditos", ReplyAction="http://tempuri.org/IWSTFD/ConsultarCreditosResponse")]
        RespuestaCreditos ConsultarCreditos(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ConsultarCreditos", ReplyAction="http://tempuri.org/IWSTFD/ConsultarCreditosResponse")]
        System.Threading.Tasks.Task<RespuestaCreditos> ConsultarCreditosAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ConsultarComprobantes", ReplyAction="http://tempuri.org/IWSTFD/ConsultarComprobantesResponse")]
        RespuestaReporte ConsultarComprobantes(string usuario, string password, System.DateTime fechaInicial, System.DateTime fechaFinal, int filaInicial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTFD/ConsultarComprobantes", ReplyAction="http://tempuri.org/IWSTFD/ConsultarComprobantesResponse")]
        System.Threading.Tasks.Task<RespuestaReporte> ConsultarComprobantesAsync(string usuario, string password, System.DateTime fechaInicial, System.DateTime fechaFinal, int filaInicial);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSTFDChannel : IWSTFD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTFDClient : System.ServiceModel.ClientBase<IWSTFD>, IWSTFD {
        
        public WSTFDClient() {
        }
        
        public WSTFDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTFDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTFDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        
		public WSTFDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RespuestaTFD TimbrarCFDI(string usuario, string password, string cadenaXML, string referencia) {

			return base.Channel.TimbrarCFDI(usuario, password, cadenaXML, referencia);
        }
        
        public System.Threading.Tasks.Task<RespuestaTFD> TimbrarCFDIAsync(string usuario, string password, string cadenaXML, string referencia) {
            return base.Channel.TimbrarCFDIAsync(usuario, password, cadenaXML, referencia);
        }
        
        public RespuestaCancelacion CancelarCFDI(string usuario, string password, string rFCEmisor, string[] listaCFDI, string clavePrivada_Base64, string passwordClavePrivada) {
            return base.Channel.CancelarCFDI(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada);
        }
        
        public System.Threading.Tasks.Task<RespuestaCancelacion> CancelarCFDIAsync(string usuario, string password, string rFCEmisor, string[] listaCFDI, string clavePrivada_Base64, string passwordClavePrivada) {
            return base.Channel.CancelarCFDIAsync(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada);
        }
        
        public RespuestaTFD TimbrarCFDTestSectorPrimario(string usuario, string password, string cadenaXML, string referencia) {
            return base.Channel.TimbrarCFDTestSectorPrimario(usuario, password, cadenaXML, referencia);
        }
        
        public System.Threading.Tasks.Task<RespuestaTFD> TimbrarCFDTestSectorPrimarioAsync(string usuario, string password, string cadenaXML, string referencia) {
            return base.Channel.TimbrarCFDTestSectorPrimarioAsync(usuario, password, cadenaXML, referencia);
        }
        
        public RespuestaTFD ObtenerPDF(string usuario, string password, string uUID, string LogoBase64) {
            return base.Channel.ObtenerPDF(usuario, password, uUID, LogoBase64);
        }
        
        public System.Threading.Tasks.Task<RespuestaTFD> ObtenerPDFAsync(string usuario, string password, string uUID, string LogoBase64) {
            return base.Channel.ObtenerPDFAsync(usuario, password, uUID, LogoBase64);
        }
        
        public RespuestaTFD ObtenerAcuseEnvio(string usuario, string password, string uUID) {
            return base.Channel.ObtenerAcuseEnvio(usuario, password, uUID);
        }
        
        public System.Threading.Tasks.Task<RespuestaTFD> ObtenerAcuseEnvioAsync(string usuario, string password, string uUID) {
            return base.Channel.ObtenerAcuseEnvioAsync(usuario, password, uUID);
        }
        
        public RespuestaTFD ObtenerAcuseCancelacion(string usuario, string password, string uUID) {
            return base.Channel.ObtenerAcuseCancelacion(usuario, password, uUID);
        }
        
        public System.Threading.Tasks.Task<RespuestaTFD> ObtenerAcuseCancelacionAsync(string usuario, string password, string uUID) {
            return base.Channel.ObtenerAcuseCancelacionAsync(usuario, password, uUID);
        }
        
        public RespuestaTFD CambiarPassword(string usuario, string passwordActual, string passwordNuevo) {
            return base.Channel.CambiarPassword(usuario, passwordActual, passwordNuevo);
        }
        
        public System.Threading.Tasks.Task<RespuestaTFD> CambiarPasswordAsync(string usuario, string passwordActual, string passwordNuevo) {
            return base.Channel.CambiarPasswordAsync(usuario, passwordActual, passwordNuevo);
        }
        
        public RespuestaTFD ConsultarComplementoTimbre(string usuario, string password, string uUID) {
            return base.Channel.ConsultarComplementoTimbre(usuario, password, uUID);
        }
        
        public System.Threading.Tasks.Task<RespuestaTFD> ConsultarComplementoTimbreAsync(string usuario, string password, string uUID) {
            return base.Channel.ConsultarComplementoTimbreAsync(usuario, password, uUID);
        }
        
        public RespuestaTFD ConsultarTimbrePorReferencia(string usuario, string password, string referencia) {
            return base.Channel.ConsultarTimbrePorReferencia(usuario, password, referencia);
        }
        
        public System.Threading.Tasks.Task<RespuestaTFD> ConsultarTimbrePorReferenciaAsync(string usuario, string password, string referencia) {
            return base.Channel.ConsultarTimbrePorReferenciaAsync(usuario, password, referencia);
        }
        
        public RespuestaCreditos ConsultarCreditos(string usuario, string password) {
            return base.Channel.ConsultarCreditos(usuario, password);
        }
        
        public System.Threading.Tasks.Task<RespuestaCreditos> ConsultarCreditosAsync(string usuario, string password) {
            return base.Channel.ConsultarCreditosAsync(usuario, password);
        }
        
        public RespuestaReporte ConsultarComprobantes(string usuario, string password, System.DateTime fechaInicial, System.DateTime fechaFinal, int filaInicial) {
            return base.Channel.ConsultarComprobantes(usuario, password, fechaInicial, fechaFinal, filaInicial);
        }
        
        public System.Threading.Tasks.Task<RespuestaReporte> ConsultarComprobantesAsync(string usuario, string password, System.DateTime fechaInicial, System.DateTime fechaFinal, int filaInicial) {
            return base.Channel.ConsultarComprobantesAsync(usuario, password, fechaInicial, fechaFinal, filaInicial);
        }
    }
}
